### PR TITLE
Switch git:// to https:// to make it all work again

### PR DESCRIPTION
**Pull request by sonic011gamer**
Because git things, 
I'll have to do it all on the main branch too

### CODE REVIEW

**Comment by M1cha** [comment]
what exactly doesn't work with the git protocol?

**Comment by sonic011gamer** [comment]
> what exactly doesn't work with the git protocol?

apparently git protocol is considered unsecure since last year, and now it refuses to clone anything, exiting with the following:
"fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
"
I suppose we could specify another port to make it work, but imho it's easier to change to https.

**Comment by M1cha** [comment]
if I understand that correctly changing it to `ssh://` would work as well.
No idea if that has other downsides though.

We use those URLs because it allows you to simply push using your ssh keys from within a repo directory without adding an ssh remote first(https is usually not used for pushing since it requires insecure and annoying password authentication)

**Comment by sonic011gamer** [comment]
> if I understand that correctly changing it to `ssh://` would work as well. No idea if that has other downsides though.
> 
> We use those URLs because it allows you to simply push using your ssh keys from within a repo directory without adding an ssh remote first(https is usually not used for pushing since it requires insecure and annoying password authentication)

I'm down for whatever works better, I just wanted to bring this to light, as to not be future issues, even if the project is "dead".

**Comment by M1cha** [comment]
Well something inconvenient is better than something broken so I'm fine with merging this.

Do you have bigger plans or why did you put dead in quotes? 😄

**Comment by sonic011gamer** [comment]
> Well something inconvenient is better than something broken so I'm fine with merging this.
> 
> Do you have bigger plans or why did you put dead in quotes? 😄

I would like to not think of it as "dead" but "stagnated" :D

**Comment by sonic011gamer** [comment]
And yeah it would be cool to revive EFIdroid at some point, right now I'm trying to gain experience 😆

**Review by M1cha — APPROVED** [review]

**Pull request merged**
